-- PostgreSQL version of dbDROP.sql

-- Triggers
DROP TRIGGER IF EXISTS AD_DISH_MENU_LOG ON DISH;
DROP TRIGGER IF EXISTS AU_DISH_MENU_LOG ON DISH;
DROP TRIGGER IF EXISTS AI_DISH_MENU_LOG ON DISH;
DROP TRIGGER IF EXISTS AD_ORDER_ITEM_REFRESH_TOTAL ON ORDER_ITEM;
DROP TRIGGER IF EXISTS AU_ORDER_ITEM_REFRESH_TOTAL ON ORDER_ITEM;
DROP TRIGGER IF EXISTS AI_ORDER_ITEM_REFRESH_TOTAL ON ORDER_ITEM;
DROP TRIGGER IF EXISTS BU_ORDER_ITEM_VALIDATE_AND_PRICE ON ORDER_ITEM;
DROP TRIGGER IF EXISTS BI_ORDER_ITEM_VALIDATE_AND_PRICE ON ORDER_ITEM;
DROP TRIGGER IF EXISTS BU_SCHEDULE_NO_OVERLAP ON SCHEDULE;
DROP TRIGGER IF EXISTS BI_SCHEDULE_NO_OVERLAP ON SCHEDULE;

-- Trigger functions
DROP FUNCTION IF EXISTS TRG_AD_DISH_MENU_LOG_FN();
DROP FUNCTION IF EXISTS TRG_AU_DISH_MENU_LOG_FN();
DROP FUNCTION IF EXISTS TRG_AI_DISH_MENU_LOG_FN();
DROP FUNCTION IF EXISTS TRG_AD_ORDER_ITEM_REFRESH_TOTAL_FN();
DROP FUNCTION IF EXISTS TRG_AU_ORDER_ITEM_REFRESH_TOTAL_FN();
DROP FUNCTION IF EXISTS TRG_AI_ORDER_ITEM_REFRESH_TOTAL_FN();
DROP FUNCTION IF EXISTS TRG_BU_ORDER_ITEM_VALIDATE_AND_PRICE_FN();
DROP FUNCTION IF EXISTS TRG_BI_ORDER_ITEM_VALIDATE_AND_PRICE_FN();
DROP FUNCTION IF EXISTS TRG_BU_SCHEDULE_NO_OVERLAP_FN();
DROP FUNCTION IF EXISTS TRG_BI_SCHEDULE_NO_OVERLAP_FN();

-- Utility functions
DROP FUNCTION IF EXISTS FN_UPCOMING_EVENT_COUNT();
DROP FUNCTION IF EXISTS SP_REFRESH_ORDER_TOTAL(INT);

DROP VIEW IF EXISTS v_active_menu_items;

-- Tables
DROP TABLE IF EXISTS MENU_LOG CASCADE;
DROP TABLE IF EXISTS ORDER_ITEM CASCADE;
DROP TABLE IF EXISTS EVENT_BOOKING CASCADE;
DROP TABLE IF EXISTS INVENTORY CASCADE;
DROP TABLE IF EXISTS DISH_INGREDIENT CASCADE;
DROP TABLE IF EXISTS DRIVER CASCADE;
DROP TABLE IF EXISTS MANAGER CASCADE;
DROP TABLE IF EXISTS ORDERS CASCADE;
DROP TABLE IF EXISTS EVENT CASCADE;
DROP TABLE IF EXISTS DISH CASCADE;
DROP TABLE IF EXISTS INGREDIENT CASCADE;
DROP TABLE IF EXISTS MENU CASCADE;
DROP TABLE IF EXISTS SCHEDULE CASCADE;
DROP TABLE IF EXISTS EMPLOYEE CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;
DROP TABLE IF EXISTS LOCATION CASCADE;
DROP TABLE IF EXISTS FOOD_TRUCK CASCADE;

-- Enum types
DROP TYPE IF EXISTS menu_log_action;
DROP TYPE IF EXISTS order_status;
DROP TYPE IF EXISTS truck_status;
